name: Pull request Workflow
on:
  pull_request:
    branches:
      - -main
jobs:
  test-u:
    runs-on: ubuntu-latest
    steps:
      - name: récupération de java
        uses: actions/checkout@v2
      - name: récupération de java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
        run: mvn test
  build-app: #recup jar
    needs: test-u
    runs-on: ubuntu-latest #server
    steps:
      - name: récupération de java
        uses: actions/checkout@v2 #recup repo
      - name: récupération de java
        uses: actions/setup-java@v2 #recup  adopt jdk
        with:
          distribution: adopt
          java-version: 11
      - name: création du jar
        run: mvn package # création du jar .
      - name: upload du jar
        uses: actions/upload-artifact@v2   # upload jar
        with:
          name: app.jar #lui donne un nom
          path: ./target/testDemo-0.0.1-SNAPSHOT.jar  #chemin du jar .######