name: Workflow push
on:
  push:
jobs:
  test-unitaire:
    runs-on: ubuntu-latest
    steps:
      - name: Récuperation du repo
        uses: actions/checkout@v2
      - name: Récuperation de java
        uses: actions/setup-java@v2 #adopt Open JDK 11
        with:
          distribution: adopt
          java-version: 11
      - name: Execution des tests
        run: mvn test #test exuecute
  build-app: #recup jar
    needs: test-unitaire
    runs-on: ubuntu-latest #server
    steps:
      - name: Récuperation du repo
        uses: actions/checkout@v2
      - name: Récuperation de java
        uses: actions/setup-java@v2 #adopt Open JDK 11
        with:
          distribution: adopt
          java-version: 11
      - name: Execution des tests
        run: mvn package #test exuecute
      - name: upload du jar
        uses: actions/upload-artifact@v2   # upload jar
        with:
          name: app.jar #lui donne un nom
          path: ./target/testDemo-0.0.1-SNAPSHOT.jar  #chemin du jar .######