name: Workflow pull request
on:
  pull_request:
    branches:
      - main
jobs:
  test-unitaire:
    runs-on: ubuntu-latest
    steps:
      - name: Récuperation du repo
        uses: actions/checkout@v2 #recup repo
      - name: Récuperation de java
        uses: actions/setup-java@v2 #adopt Open JDK 11
        with:
          distribution: adopt
          java-version: 11
      - name: Execution des tests
        run: mvn test #test exuecute
  build-app: #recup jar
    needs: test-unitaire
    runs-on: ubuntu-latest #server
    steps:
      - name: Récuperation du repo
        uses: actions/checkout@v2
      - name: Récuperation de java
        uses: actions/setup-java@v2 #adopt Open JDK 11
        with:
          distribution: adopt
          java-version: 11
      - name: Execution des tests
        run: mvn package #test exuecute
      - name: upload du jar
        uses: actions/upload-artifact@v2   # upload jar
        with:
          name: app.jar #lui donne un nom
          path: ./target/testDemo-0.0.1-SNAPSHOT.jar  #chemin du jar .######
  docker:
    needs: build-app
    runs-on: ubuntu-latest
    steps:
      - name: Récuperation du repo #recup repo pour utiliser Docker file pour build push image .
        uses: actions/checkout@v2
      - name: Récuperation du JAR   # recup tout le jar
        uses: actions/download-artifact@v2
        with:
          name: app.jar   # je lui donne un nom à mon jar avec with  je recupere bien mon jar
      - name: Install QEMU Docker  #  qemu pour faire foncionner docker
        uses: docker/setup-qemu-action@v1
      - name: Install BuildX docker
        uses: docker/setup-buildx-action@v1
      - name: Connection à docker
        uses: docker/login-action@v1   #se connecter
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # dans github je place username et password
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build et push mon image docker
        uses: docker/build-push-action@v2
        with:
          context: .   #Docker file donc à la racine
          push: true #oui
          tags: progfiler/testdemo:latest   #nom image