name: workflow push
on:
  push:
jobs:
   test-unitaire:
     runs-on: ubuntu-latest
     steps:
       - name: récupération de java
         uses: actions/checkout@v2
       - name: récupération de java
         uses: actions/setup-java@v2
         with:
           distribtion: adopt
           java-version: 11
         run: mvn test